services:
  reader:
    # image: karthikeyatumpudi/reader
    volumes:
      - ./shared:/shared
    build: 
      context: ./Reader_app
      dockerfile: Dockerfile
    depends_on:
      - writer
  writer:
    # image: karthikeyatumpudi/writer
    volumes:
      - ./shared:/shared
    build: 
      context: ./Writer_app
      dockerfile: Dockerfile